// Auto-generated by tools/scripts/generate_voice_capability_manifest.py
export const GENERATED_VOICE_CAPABILITY_MANIFEST = {
  "noise_cancellation": {
    "models": [
      {
        "defaults": {},
        "editor_fields": [],
        "editor_visible": true,
        "id": "nc",
        "label": "nc",
        "runtime_supported": true,
        "runtime_value": null
      },
      {
        "defaults": {},
        "editor_fields": [],
        "editor_visible": true,
        "id": "bvc",
        "label": "bvc",
        "runtime_supported": true,
        "runtime_value": null
      },
      {
        "defaults": {},
        "editor_fields": [],
        "editor_visible": true,
        "id": "bvc_telephony",
        "label": "bvc_telephony",
        "runtime_supported": true,
        "runtime_value": null
      }
    ],
    "providers": [
      {
        "defaults": {
          "model": "bvc"
        },
        "editor_fields": [
          "model"
        ],
        "editor_visible": true,
        "id": "krisp",
        "label": "krisp",
        "runtime_supported": true,
        "runtime_value": null
      }
    ]
  },
  "stt": {
    "providers": [
      {
        "defaults": {
          "language": "en"
        },
        "editor_fields": [
          "model",
          "language",
          "location"
        ],
        "editor_visible": true,
        "id": "google",
        "label": "google",
        "runtime_supported": true,
        "runtime_value": null
      },
      {
        "defaults": {
          "enable_language_identification": true,
          "enable_speaker_diarization": false,
          "language": "en",
          "language_hints_strict": false
        },
        "editor_fields": [
          "model",
          "language",
          "location",
          "language_hints",
          "language_hints_strict",
          "enable_language_identification",
          "enable_speaker_diarization",
          "enable_endpoint_detection",
          "max_endpoint_delay_ms"
        ],
        "editor_visible": true,
        "id": "soniox",
        "label": "soniox",
        "runtime_supported": true,
        "runtime_value": null
      },
      {
        "defaults": {},
        "editor_fields": [
          "model",
          "language"
        ],
        "editor_visible": false,
        "id": "test",
        "label": "test",
        "runtime_supported": true,
        "runtime_value": null
      },
      {
        "defaults": {},
        "editor_fields": [
          "model",
          "language"
        ],
        "editor_visible": false,
        "id": "noop",
        "label": "noop",
        "runtime_supported": true,
        "runtime_value": null
      }
    ]
  },
  "tts": {
    "providers": [
      {
        "defaults": {
          "language": "en-US"
        },
        "editor_fields": [
          "voice_name",
          "language",
          "location"
        ],
        "editor_visible": true,
        "id": "google",
        "label": "google",
        "runtime_supported": true,
        "runtime_value": null
      },
      {
        "defaults": {
          "model": "eleven_turbo_v2_5"
        },
        "editor_fields": [
          "model",
          "voice_id",
          "language"
        ],
        "editor_visible": true,
        "id": "elevenlabs",
        "label": "elevenlabs",
        "runtime_supported": true,
        "runtime_value": null
      },
      {
        "defaults": {},
        "editor_fields": [],
        "editor_visible": false,
        "id": "test",
        "label": "test",
        "runtime_supported": true,
        "runtime_value": null
      },
      {
        "defaults": {},
        "editor_fields": [],
        "editor_visible": false,
        "id": "noop",
        "label": "noop",
        "runtime_supported": true,
        "runtime_value": null
      }
    ]
  },
  "turn_detection": {
    "endpointing_modes": [
      {
        "defaults": {},
        "editor_fields": [],
        "editor_visible": true,
        "id": "fixed",
        "label": "fixed",
        "runtime_supported": true,
        "runtime_value": "fixed"
      },
      {
        "defaults": {},
        "editor_fields": [],
        "editor_visible": true,
        "id": "dynamic",
        "label": "dynamic",
        "runtime_supported": true,
        "runtime_value": "dynamic"
      }
    ],
    "interruption_modes": [
      {
        "defaults": {},
        "editor_fields": [],
        "editor_visible": true,
        "id": "adaptive",
        "label": "adaptive",
        "runtime_supported": true,
        "runtime_value": "adaptive"
      },
      {
        "defaults": {},
        "editor_fields": [],
        "editor_visible": true,
        "id": "vad",
        "label": "vad",
        "runtime_supported": true,
        "runtime_value": "vad"
      },
      {
        "defaults": {},
        "editor_fields": [],
        "editor_visible": true,
        "id": "auto",
        "label": "auto",
        "runtime_supported": true,
        "runtime_value": null
      }
    ],
    "types": [
      {
        "defaults": {},
        "editor_fields": [],
        "editor_visible": true,
        "id": "stt",
        "label": "stt",
        "runtime_supported": true,
        "runtime_value": "stt"
      },
      {
        "defaults": {},
        "editor_fields": [],
        "editor_visible": true,
        "id": "multilingual_model",
        "label": "multilingual_model",
        "runtime_supported": true,
        "runtime_value": null
      },
      {
        "defaults": {},
        "editor_fields": [],
        "editor_visible": false,
        "id": "vad",
        "label": "vad",
        "runtime_supported": true,
        "runtime_value": "vad"
      },
      {
        "defaults": {},
        "editor_fields": [],
        "editor_visible": false,
        "id": "realtime_llm",
        "label": "realtime_llm",
        "runtime_supported": true,
        "runtime_value": "realtime_llm"
      },
      {
        "defaults": {},
        "editor_fields": [],
        "editor_visible": false,
        "id": "manual",
        "label": "manual",
        "runtime_supported": true,
        "runtime_value": "manual"
      }
    ]
  }
} as const;
